--- 
- hosts: mywebserver
  become: yes
  tasks: 
  - name: install java on ubuntu node
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present 
    when: ansible_os_family =="ubuntu" 


  - name: install java on RedHat node
    ansible.builtin.dnf:
      name: "{{myjavapackonRedHat}}"
      state: present 
    when: ansible_os_family =="RedHat"