--- 
- hosts: mywebserver
  become: yes
  tasks: 
  - name: install java on ubuntu node
    apt:
      name: "{{myjavapackonubuntu}}"
      stste: present 
    when: ansible_os_family =="Debian" 


  - name: install java on amazon node
    ansible.builtin.dnf:
      name: "{{myjavapackonubuntu}}"
      stste: present 
    when: ansible_os_family =="amazon"